### ISSUE TITLE
Ubuntu 22.04 ffplay wont build

### ISSUE THREAD

**Issue by ma-blip** [slyfox1186/ffmpeg-build-script#10]
Hi Again.

Forgot to mention that ffplay does not build on a fresh install of Ubuntu 22.04.

Resolved by installing: 

sudo apt-get install libsdl2-dev

before compile. You might want to add that to your dependecies install.

Regards

**Comment by slyfox1186** [comment]
I have combed in internet for solutions. I am stumped. I have built the script on native ubuntu 22.04 and ffplay was missing then immediately booted into Windows and used WSL Debian 12 and it had ffplay when the build was finished using the exact same build script.
