### ISSUE TITLE
 Failed to execute: cmake ../../../source Building x265 on ubuntu 22.04.3

### ISSUE THREAD

**Issue by brutus009** [slyfox1186/ffmpeg-build-script#11]
Building x265 - version 8ee01d4 // im using frech ubuntu 22.04
====================================
The file "x265-8ee01d4.tar.bz2" is already downloaded.
File extracted: x265-8ee01d4.tar.bz2

$ making 12bit binaries
$ cmake ../../../source -DCMAKE_INSTALL_PREFIX=/root/ffmpeg-build-script/ffmpeg-build-script/workspace -DCMAKE_BUILD_TYPE=Release -DENABLE_CLI=OFF -DENABLE_SHARED=OFF -DEXPORT_C_API=OFF -DHIGH_BIT_DEPTH=ON -DMAIN12=ON -G Ninja -Wno-dev

Failed to execute: cmake ../../../source -DCMAKE_INSTALL_PREFIX=/root/ffmpeg-build-script/ffmpeg-build-script/workspace -DCMAKE_BUILD_TYPE=Release -DENABLE_CLI=OFF -DENABLE_SHARED=OFF -DEXPORT_C_API=OFF -DHIGH_BIT_DEPTH=ON -DMAIN12=ON -G Ninja -Wno-dev

**Comment by brutus009** [comment]
root@vmi1508026:~/ffmpeg-build-script/ffmpeg-build-script/packages/x265-8ee01d4/build/linux/12bit# cmake ../../../source -DCMAKE_INSTALL_PREFIX=/root/ffmpeg-build-script/ffmpeg-build-script/workspace -DCMAKE_BUILD_TYPE=Release -DENABLE_CLI=OFF -DENABLE_SHARED=OFF -DEXPORT_C_API=OFF -DHIGH_BIT_DEPTH=ON -DMAIN12=ON -G Ninja -Wno-dev
-- cmake version 3.22.1
-- The CXX compiler identification is Clang 14.0.0
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - failed
-- Check for working CXX compiler: /usr/lib/ccache/clang++
-- Check for working CXX compiler: /usr/lib/ccache/clang++ - broken
CMake Error at /usr/share/cmake-3.22/Modules/CMakeTestCXXCompiler.cmake:62 (message):
  The C++ compiler

    "/usr/lib/ccache/clang++"

  is not able to compile a simple test program.

  It fails with the following output:

    Change Dir: /root/ffmpeg-build-script/ffmpeg-build-script/packages/x265-8ee01d4/build/linux/12bit/CMakeFiles/CMakeTmp

    Run Build Command(s):/bin/ninja cmTC_049fa && [1/2] Building CXX object CMakeFiles/cmTC_049fa.dir/testCXXCompiler.cxx.o
    [2/2] Linking CXX executable cmTC_049fa
    FAILED: cmTC_049fa
    : && /usr/lib/ccache/clang++ -g -O3 -march=native -DHWY_COMPILE_ONLY_SCALAR -rdynamic CMakeFiles/cmTC_049fa.dir/testCXXCompiler.cxx.o -o cmTC_049fa   && :
    /usr/bin/ld: cannot find -lstdc++: No such file or directory
    clang: error: linker command failed with exit code 1 (use -v to see invocation)
    ninja: build stopped: subcommand failed.

  CMake will not be able to correctly generate this project.
Call Stack (most recent call first):
  CMakeLists.txt:19 (project)

-- Configuring incomplete, errors occurred!

**Comment by slyfox1186** [comment]
so this tells you what is wrong

```
/usr/bin/ld: cannot find -lstdc++: No such file or directory
```
you need to install this using APT.

run `sudo apt search libstdc++`

It will be a package that is named similar to the below examples.

```
libstdc++5
libstdc++6
libstdc++-11-dev
libstdc++-12-dev
```

**Comment by brutus009** [comment]
thank you boss

**Comment by slyfox1186** [comment]
I will close this since it seems this has been resolved.
