### ISSUE TITLE
Unable to locate package libnvidia-encode-545

### ISSUE THREAD

**Issue by sfahadshahzad** [slyfox1186/ffmpeg-build-script#12]
Hi,
Trying to build ffmpeg using build script and getting error.

Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
E: Unable to locate package libnvidia-encode-545

**Comment by slyfox1186** [comment]
**what version of linux are you on?**

run the command below and tell me what is the highest version show.

DO NOT forget to tell me your linux version!

```
sudo apt list libnvidia-encode-*
```

**Comment by brutus009** [comment]
thanks , did you have skype contact ? tell me , can you make a script for this configuration ?  : 
root@vmi1490501:~# /home/brutus/brutus_core/bin/ffmpeg -version
ffmpeg version N-110496-g09b2ca93b4-brutus Copyright (c) 2000-2023 the FFmpeg developers
built with gcc 12.2.0 (crosstool-NG 1.25.0.152_89671bf)
configuration: --prefix=/ffbuild/prefix --pkg-config-flags=--static --pkg-config=pkg-config --cross-prefix=x86_64-ffbuild-linux-gnu- --arch=x86_64 --target-os=linux --enable-nonfree --enable-gpl --enable-version3 --disable-debug --enable-iconv --enable-libxml2 --enable-zlib --enable-libfreetype --enable-libfribidi --enable-gmp --enable-openssl --enable-lzma --enable-fontconfig --enable-libvorbis --enable-opencl --enable-libpulse --enable-libvmaf --enable-libxcb --enable-xlib --enable-amf --enable-libaom --enable-libaribb24 --enable-avisynth --enable-chromaprint --enable-libdav1d --enable-libdavs2 --enable-libfdk-aac --enable-ffnvcodec --enable-cuda-llvm --enable-frei0r --enable-libgme --enable-libkvazaar --enable-libass --enable-libbluray --enable-libjxl --enable-libmp3lame --enable-libopus --enable-librist --enable-libssh --enable-libtheora --enable-libvpx --enable-libwebp --enable-lv2 --disable-libmfx --enable-libvpl --enable-openal --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenh264 --enable-libopenjpeg --enable-libopenmpt --enable-librav1e --enable-librubberband --disable-schannel --enable-sdl2 --enable-libsoxr --enable-libsrt --enable-libsvtav1 --enable-libtwolame --enable-libuavs3d --enable-libdrm --enable-vaapi --enable-libvidstab --enable-vulkan --enable-libshaderc --enable-libplacebo --enable-libx264 --enable-libx265 --enable-libxavs2 --enable-libxvid --enable-libzimg --enable-libzvbi --extra-cflags=-DLIBTWOLAME_STATIC --extra-cxxflags= --extra-ldflags=-pthread --extra-ldexeflags=-pie --extra-libs='-ldl -lgomp' --extra-version=brutus
libavutil      58.  7.100 / 58.  7.100
libavcodec     60. 10.100 / 60. 10.100
libavformat    60.  5.100 / 60.  5.100
libavdevice    60.  2.100 / 60.  2.100
libavfilter     9.  7.100 /  9.  7.100
libswscale      7.  2.100 /  7.  2.100
libswresample   4. 11.100 /  4. 11.100
libpostproc    57.  2.100 / 57.  2.100

**Comment by slyfox1186** [comment]
1. Probably.
2. Where did you get this version of ffmpeg if you want a script to create it from scratch?

**Comment by brutus009** [comment]
its a freind ho send it to me  , you think its a better config ? or maybe we can mix them to see what's not in one and add it to the other
ps: dont think im profetionel of ffmpeg lol im new on this , but I want to learn how to do my own build

**Comment by sfahadshahzad** [comment]
> **what version of linux are you on?**
> 
> run the command below and tell me what is the highest version show.
> 
> DO NOT forget to tell me your linux version!
> 
> ```
> sudo apt list libnvidia-encode-*
> ```

I am using Ubuntu 22.04 Jammy and I have Nvidia Quadro P2000 with driver version 535.

apt list libnvidia-encode-*
Listing... Done
libnvidia-encode-390/jammy-updates,jammy-security 390.157-0ubuntu0.22.04.2 amd64
libnvidia-encode-390/jammy-updates,jammy-security 390.157-0ubuntu0.22.04.2 i386
libnvidia-encode-418-server/jammy-updates,jammy-security 418.226.00-0ubuntu5~0.22.04.1 amd64
libnvidia-encode-418-server/jammy-updates,jammy-security 418.226.00-0ubuntu5~0.22.04.1 i386
libnvidia-encode-418/jammy 430.50-0ubuntu3 amd64
libnvidia-encode-418/jammy 430.50-0ubuntu3 i386
libnvidia-encode-430/jammy 440.100-0ubuntu1 amd64
libnvidia-encode-430/jammy 440.100-0ubuntu1 i386
libnvidia-encode-435/jammy 455.45.01-0ubuntu1 amd64
libnvidia-encode-435/jammy 455.45.01-0ubuntu1 i386
libnvidia-encode-440-server/jammy-updates,jammy-security 450.248.02-0ubuntu0.22.04.1 amd64
libnvidia-encode-440-server/jammy-updates,jammy-security 450.248.02-0ubuntu0.22.04.1 i386
libnvidia-encode-440/jammy 450.119.03-0ubuntu1 amd64
libnvidia-encode-440/jammy 450.119.03-0ubuntu1 i386
libnvidia-encode-450-server/jammy-updates,jammy-security 450.248.02-0ubuntu0.22.04.1 amd64
libnvidia-encode-450-server/jammy-updates,jammy-security 450.248.02-0ubuntu0.22.04.1 i386
libnvidia-encode-450/jammy 460.91.03-0ubuntu1 amd64
libnvidia-encode-450/jammy 460.91.03-0ubuntu1 i386
libnvidia-encode-455/jammy 460.91.03-0ubuntu1 amd64
libnvidia-encode-455/jammy 460.91.03-0ubuntu1 i386
libnvidia-encode-460-server/jammy-updates,jammy-security 470.223.02-0ubuntu0.22.04.1 amd64
libnvidia-encode-460-server/jammy-updates,jammy-security 470.223.02-0ubuntu0.22.04.1 i386
libnvidia-encode-460/jammy-updates,jammy-security 470.223.02-0ubuntu0.22.04.1 amd64
libnvidia-encode-460/jammy-updates,jammy-security 470.223.02-0ubuntu0.22.04.1 i386
libnvidia-encode-465/jammy-updates,jammy-security 470.223.02-0ubuntu0.22.04.1 amd64
libnvidia-encode-465/jammy-updates,jammy-security 470.223.02-0ubuntu0.22.04.1 i386
libnvidia-encode-470-server/jammy-updates,jammy-security 470.223.02-0ubuntu0.22.04.1 amd64
libnvidia-encode-470-server/jammy-updates,jammy-security 470.223.02-0ubuntu0.22.04.1 i386
libnvidia-encode-470/jammy-updates,jammy-security 470.223.02-0ubuntu0.22.04.1 amd64
libnvidia-encode-470/jammy-updates,jammy-security 470.223.02-0ubuntu0.22.04.1 i386
libnvidia-encode-495/jammy-updates,jammy-security 510.108.03-0ubuntu0.22.04.1 amd64
libnvidia-encode-495/jammy-updates,jammy-security 510.108.03-0ubuntu0.22.04.1 i386
libnvidia-encode-510-server/jammy-updates,jammy-security 515.105.01-0ubuntu0.22.04.1 amd64
libnvidia-encode-510-server/jammy-updates,jammy-security 515.105.01-0ubuntu0.22.04.1 i386
libnvidia-encode-510/jammy-updates,jammy-security 525.147.05-0ubuntu0.22.04.1 amd64
libnvidia-encode-510/jammy-updates,jammy-security 525.147.05-0ubuntu0.22.04.1 i386
libnvidia-encode-515-server/jammy-updates,jammy-security 525.147.05-0ubuntu0.22.04.1 amd64
libnvidia-encode-515-server/jammy-updates,jammy-security 525.147.05-0ubuntu0.22.04.1 i386
libnvidia-encode-515/jammy-updates,jammy-security 525.147.05-0ubuntu0.22.04.1 amd64
libnvidia-encode-515/jammy-updates,jammy-security 525.147.05-0ubuntu0.22.04.1 i386
libnvidia-encode-520/jammy-updates,jammy-security 525.147.05-0ubuntu0.22.04.1 amd64
libnvidia-encode-520/jammy-updates,jammy-security 525.147.05-0ubuntu0.22.04.1 i386
libnvidia-encode-525-server/jammy-updates,jammy-security 525.147.05-0ubuntu0.22.04.1 amd64
libnvidia-encode-525-server/jammy-updates,jammy-security 525.147.05-0ubuntu0.22.04.1 i386
libnvidia-encode-525/jammy-updates,jammy-security 525.147.05-0ubuntu0.22.04.1 amd64
libnvidia-encode-525/jammy-updates,jammy-security 525.147.05-0ubuntu0.22.04.1 i386
libnvidia-encode-530/jammy-updates,jammy-security 535.129.03-0ubuntu0.22.04.1 amd64
libnvidia-encode-530/jammy-updates,jammy-security 535.129.03-0ubuntu0.22.04.1 i386
libnvidia-encode-535-server/jammy-updates,jammy-security 535.129.03-0ubuntu0.22.04.1 amd64
libnvidia-encode-535-server/jammy-updates,jammy-security 535.129.03-0ubuntu0.22.04.1 i386
libnvidia-encode-535/jammy-updates,jammy-security,now 535.129.03-0ubuntu0.22.04.1 amd64 [installed,automatic]
libnvidia-encode-535/jammy-updates,jammy-security,now 535.129.03-0ubuntu0.22.04.1 i386 [installed,automatic]


Regards,

Fahad

**Comment by slyfox1186** [comment]
I have made changes to the `ubuntu_os_ver_fn()` function. Hopefully this will solve your issue.

**Comment by slyfox1186** [comment]
> its a freind ho send it to me , you think its a better config ? or maybe we can mix them to see what's not in one and add it to the other ps: dont think im profetionel of ffmpeg lol im new on this , but I want to learn how to do my own build

I think that my script will do just about whatever FFmpeg is capable of because it sources the latest code for the majority of the optional addon libraries. The biggest thing about what makes FFmpeg better is your hardware. The high end video cards and CPU's are going to make a huge difference in the speed and overall quality and compression potential. The build script is key to building a foundation of software, but the hardware and the command line are just as important.

**Comment by slyfox1186** [comment]
If you still have issues let me know otherwise I will close this.
