### ISSUE TITLE
Error while building x265

### ISSUE THREAD

**Issue by sfahadshahzad** [slyfox1186/ffmpeg-build-script#14]
Building x265 - version 8ee01d4
====================================
Downloading "https://bitbucket.org/multicoreware/x265_git/get/8ee01d45b05cdbc9da89b884815257807a514bc8.tar.bz2" saving as "x265-8ee01d4.tar.bz2"
Download Completed
File extracted: x265-8ee01d4.tar.bz2

$ making 12bit binaries
$ cmake ../../../source -DCMAKE_INSTALL_PREFIX=/usr/local -DCMAKE_BUILD_TYPE=Release -DENABLE_CLI=OFF -DENABLE_SHARED=OFF -DEXPORT_C_API=OFF -DHIGH_BIT_DEPTH=ON -DMAIN12=ON -G Ninja -Wno-dev
CMake Error at /usr/share/cmake-3.22/Modules/CMakeTestCXXCompiler.cmake:62 (message):
  The C++ compiler

    "/usr/lib/ccache/clang++"

  is not able to compile a simple test program.

  It fails with the following output:

    Change Dir: /home/encoder/ffmpeg-build-script/ffmpeg-build-script/packages/x265-8ee01d4/build/linux/12bit/CMakeFiles/CMakeTmp
    
    Run Build Command(s):/bin/ninja cmTC_0a7fd && [1/2] Building CXX object CMakeFiles/cmTC_0a7fd.dir/testCXXCompiler.cxx.o
    [2/2] Linking CXX executable cmTC_0a7fd
    FAILED: cmTC_0a7fd 
    : && /usr/lib/ccache/clang++ -g -O3 -march=native -DHWY_COMPILE_ONLY_SCALAR -DHWY_COMPILE_ALL_ATTAINABLE -L/home/encoder/ffmpeg-build-script/ffmpeg-build-script/workspace/lib64 -L/home/encoder/ffmpeg-build-script/ffmpeg-build-script/workspace/lib -L/home/encoder/ffmpeg-build-script/ffmpeg-build-script/workspace/lib/x86_64-linux-gnu -L/usr/local/lib64 -L/usr/local/lib -L/usr/lib/x86_64-linux-gnu -L/usr/lib64 -L/usr/lib -L/lib64 -L/lib -DLIBXML_STATIC   -rdynamic CMakeFiles/cmTC_0a7fd.dir/testCXXCompiler.cxx.o -o cmTC_0a7fd   && :
    /bin/ld: cannot find -lstdc++: No such file or directory
    clang: error: linker command failed with exit code 1 (use -v to see invocation)
    ninja: build stopped: subcommand failed.
    
    

  

  CMake will not be able to correctly generate this project.
Call Stack (most recent call first):
  CMakeLists.txt:19 (project)

Failed to execute: cmake ../../../source -DCMAKE_INSTALL_PREFIX=/usr/local -DCMAKE_BUILD_TYPE=Release -DENABLE_CLI=OFF -DENABLE_SHARED=OFF -DEXPORT_C_API=OFF -DHIGH_BIT_DEPTH=ON -DMAIN12=ON -G Ninja -Wno-dev

To report a bug create an issue at: https://github.com/slyfox1186/ffmpeg-build-script/issues

**Comment by slyfox1186** [comment]
This was already dealt with.

https://github.com/slyfox1186/ffmpeg-build-script/issues/11#issuecomment-1799192492
