### ISSUE TITLE
disable installation of nvidia driver in bash script

### ISSUE THREAD

**Issue by brutus009** [slyfox1186/ffmpeg-build-script#15]
how i can disable installation of nvidia driver in bash script ?
i need to install nvidia-driver-545 to make it work  but eash time i run the bash script of build he install nvidia-driver-535 
and this give me error here , im on ubuntu 22.04

 version 5.3.5 : 
command :  nvidia-smi --query-gpu=gpu_name --format=csv | sort -r | head -n 1
result : NVML library version: 535.129

version 5.4.5 : 
command : nvidia-smi --query-gpu=gpu_name --format=csv | sort -r | head -n 1
result : NVIDIA GeForce GTX 1080

this give me problem on this function : gpu_arch_fn()

**Comment by slyfox1186** [comment]
1. download the script

```
git clone https://github.com/slyfox1186/ffmpeg-build-script.git
```
3. replace all found text `nvidia-driver-535` with `nvidia-driver-545`

4. run the script

```
bash build-ffmpeg --build --latest
```
