### ISSUE TITLE
ffmpeg source link expired

### ISSUE THREAD

**Issue by sfahadshahzad** [slyfox1186/ffmpeg-build-script#16]
Building ffmpeg - version e531aba
====================================
Downloading "https://git.ffmpeg.org/gitweb/ffmpeg.git/snapshot/e531abaf3c41953618573bef9a2568f7644626b6.tar.gz" saving as "ffmpeg-e531aba.tar.gz"

The script failed to download "ffmpeg-e531aba.tar.gz" and will try again in 10 seconds...

The script failed to download "ffmpeg-e531aba.tar.gz" twice and will now exit. Line: 258

To report a bug create an issue at: https://github.com/slyfox1186/ffmpeg-build-script/issues

**Comment by slyfox1186** [comment]
It shouldnt even use that link. It is suppose to use a git pull. I will look into it.

**Comment by slyfox1186** [comment]
You need to update to the latest script.

**Comment by slyfox1186** [comment]
re-open this if this is still a problem for you.
