### ISSUE TITLE
pulseaudio is not compiled statically  

### ISSUE THREAD

**Issue by brutus009** [slyfox1186/ffmpeg-build-script#17]
pulseaudio is not compiled statically if I move the bin to another ubuntu 22.04 it is necessary to compile pulse audio, is it possible to have it static?

**Comment by slyfox1186** [comment]
Give it a try. Download the script. Make the changes necessary and let me
know!

**Comment by brutus009** [comment]
no same the build is ok but the libpulse.a are not generated for a static build
i will try in frech ubuntu again and let you know

**Comment by brutus009** [comment]
something wrong with : libunwind-dev libv4l-dev libva-dev
we need i think to have this installed libc++-dev , but there is a conflict

**Comment by brutus009** [comment]
i think the version 16.99 dont have static library need to change version

**Comment by slyfox1186** [comment]
If you have any new information to help get this going please re-open this.

**Comment by brutus009** [comment]
so i found a solution but not with new version , i do it staticly with old version of pulseaudio 14.2
