### ISSUE TITLE
openssl and librtmp

### ISSUE THREAD

**Issue by brutus009** [slyfox1186/ffmpeg-build-script#19]
did you config work with rtmpdump ? librtmp ?

**Comment by slyfox1186** [comment]
I have been on Thanksgiving holiday with family. I will check back on this later this week. Keep posted.

By the way... I see that you have not starred the repo. Would you mind doing that?

**Comment by slyfox1186** [comment]
No I have not done anything with this.

**Comment by slyfox1186** [comment]
Since I have nothing to add at this time I will close this for now.
