### ISSUE TITLE
Unable to locate package librist-dev

### ISSUE THREAD

**Issue by djlongy** [slyfox1186/ffmpeg-build-script#2]
Running 22.04.3 LTS (Jammy Jellyfish)
script fails with 
E: Unable to locate package librist-dev
Doesn't seem like this package exists on the jammy repo.
Only on kinetic, lunar and mantic

**Comment by slyfox1186** [comment]
Nice thanks for pointing this out. I will make changes to the script.

**Comment by slyfox1186** [comment]
If you see anything else just let me know. Thanks.
