### ISSUE TITLE
support for latest 2310 ubuntu

### ISSUE THREAD

**Issue by krzemienski** [slyfox1186/ffmpeg-build-script#21]
------------------------------  
|                              |  
| FFmpeg Build Script - v3.1.6 |  
|                              |  
\------------------------------

The script will utilize (64) CPU threads for parallel processing to accelerate the build speed.

  
Could not detect the Ubuntu version. Line: 1183

To report a bug create an issue at: https://github.com/slyfox1186/ffmpeg-build-script/issues

**Comment by slyfox1186** [comment]
You need to help me out here.

This should have been in your original post.

```
What version of UBUNTU DO YOU HAVE
```

**Comment by krzemienski** [comment]
> You need to help me out here.
> 
> 
> 
> This should have been in your original post.
> 
> 
> 
> ```
> 
> What version of UBUNTU DO YOU HAVE
> 
> ```

Sorry yes I should have! It was in the issue title, 
Ubuntu 23.10 (Mantic Minotaur)

**Comment by slyfox1186** [comment]
Ok I will work on adding support for this. Stand by.

**Comment by slyfox1186** [comment]
If you care to search the code you will see that I have added "23.10" at multiple spots in the code. This should verify your Ubuntu version.

HOWEVER,

I do not have that version. If you find there are missing packages or other bugs, report them and I will fix it according to what you bring me.

Thanks for supporting this repo and have a great build!

**Comment by nbrewk** [comment]
I'm unable to build on Mantic as the following packages aren't found by APT:

> E: Unable to locate package libamd2
> E: Unable to locate package libcamd2
> E: Unable to locate package libccolamd2
> E: Unable to locate package libcholmod3
> E: Unable to locate package libcolamd2
> E: Unable to locate package libsuitesparseconfig5
> E: Unable to locate package libumfpack5
