### ISSUE TITLE
Problems with arch linux (Garuda) (re-open)

### ISSUE THREAD

**Issue by Hubfront** [slyfox1186/ffmpeg-build-script#22]
Hi slyfox,

thank you. Going with option 2 (without CUDA) results in

Unable to locate the file: /usr/local/cuda/version.json. Line: 877

To report a bug create an issue at: https://github.com/slyfox1186/ffmpeg-build-script/issues

Option 1 results in 

Downloading CUDA SDK Toolkit - version 12.3.1
====================================================

==> Erstelle Paket: cuda 12.3.0-6 (Mo 04 Dez 2023 21:07:04 CET)
==> Prüfe Laufzeit-Abhängigkeiten...
==> Prüfe Buildtime-Abhängigkeiten...
==> Empfange Quellen...
-> Lade cuda_12.3.0_545.23.06_linux.run herunter...
% Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
Dload  Upload   Total   Spent    Left  Speed
100 4158M  100 4158M    0     0  71.5M      0  0:00:58  0:00:58 --:--:-- 73.0M
-> cuda.sh gefunden
-> cuda.conf gefunden
-> accinj64.pc gefunden
-> cublas.pc gefunden
-> cuda.pc gefunden
-> cudart.pc gefunden
-> cufft.pc gefunden
-> cufftw.pc gefunden
-> cuinj64.pc gefunden
-> curand.pc gefunden
-> cusolver.pc gefunden
-> cusparse.pc gefunden
-> nppc.pc gefunden
-> nppial.pc gefunden
-> nppicc.pc gefunden
-> nppicom.pc gefunden
-> nppidei.pc gefunden
-> nppif.pc gefunden
-> nppig.pc gefunden
-> nppim.pc gefunden
-> nppi.pc gefunden
-> nppist.pc gefunden
-> nppisu.pc gefunden
-> nppitc.pc gefunden
-> npps.pc gefunden
-> nvgraph.pc gefunden
-> nvidia-ml.pc gefunden
-> nvjpeg.pc gefunden
-> nvrtc.pc gefunden
-> nvToolsExt.pc gefunden
==> Überprüfe source Dateien mit sha512sums...
cuda_12.3.0_545.23.06_linux.run ... Erfolg
cuda.sh ... Erfolg
cuda.conf ... Erfolg
accinj64.pc ... Erfolg
cublas.pc ... Erfolg
cuda.pc ... Erfolg
cudart.pc ... Erfolg
cufft.pc ... Erfolg
cufftw.pc ... Erfolg
cuinj64.pc ... Erfolg
curand.pc ... Erfolg
cusolver.pc ... Erfolg
cusparse.pc ... Erfolg
nppc.pc ... Erfolg
nppial.pc ... Erfolg
nppicc.pc ... Erfolg
nppicom.pc ... Erfolg
nppidei.pc ... Erfolg
nppif.pc ... Erfolg
nppig.pc ... Erfolg
nppim.pc ... Erfolg
nppi.pc ... Erfolg
nppist.pc ... Erfolg
nppisu.pc ... Erfolg
nppitc.pc ... Erfolg
npps.pc ... Erfolg
nvgraph.pc ... Erfolg
nvidia-ml.pc ... Erfolg
nvjpeg.pc ... Erfolg
nvrtc.pc ... Erfolg
nvToolsExt.pc ... Erfolg
==> Entferne existierendes $srcdir/ Verzeichnis...
==> Entpacke Quellen...
==> Beginne prepare()...
Creating directory /home/matthias/Downloads/ffmpeg-build-script/cuda/src
==> Beginne build()...
==> Betrete fakeroot Umgebung...
==> Beginne package_cuda()...
==> Säubere Installation...
-> Entferne libtool Dateien...
-> Bereinige ungewollte Dateien...
-> Komprimiere Man-Pages und Info-Seiten...
==> Prüfe auf Paketierungsprobleme...
==> Erstelle Paket "cuda"...
-> Erstelle .PKGINFO Datei...
-> Erstelle .BUILDINFO Datei...
-> Füge install Datei hinzu...
-> Erstelle .MTREE-Datei...
-> Komprimiere Paket...
==> Beginne package_cuda-tools()...
==> Säubere Installation...
-> Entferne libtool Dateien...
-> Bereinige ungewollte Dateien...
-> Komprimiere Man-Pages und Info-Seiten...
==> Prüfe auf Paketierungsprobleme...
==> Erstelle Paket "cuda-tools"...
-> Erstelle .PKGINFO Datei...
-> Erstelle .BUILDINFO Datei...
-> Füge install Datei hinzu...
-> Erstelle .MTREE-Datei...
-> Komprimiere Paket...
==> Verlasse fakeroot Umgebung.
==> Beendete Erstellung: cuda 12.3.0-6 (Mo 04 Dez 2023 21:09:33 CET)
==> Installiere Paketgruppe cuda mit pacman -U...
Pakete werden geladen …
Warnung: cuda-12.3.0-6 ist aktuell -- Überspringe
Warnung: cuda-tools-12.3.0-6 ist aktuell -- Überspringe
Es gibt nichts zu tun

Unable to locate the file: /usr/local/cuda/version.json. Line: 877

By the way, I did not find a way to reopen the issue.

_Originally posted by @Hubfront in https://github.com/slyfox1186/ffmpeg-build-script/issues/20#issuecomment-1839400433_

**Comment by slyfox1186** [comment]
dang, sorry about that, i will get this fixed... just hang on a little longer for me.

**Comment by slyfox1186** [comment]
OK I used my AMD GPU this time and was able to compile FFmpeg at the scripts end. I added a bypass that detects the GPU version and if it detects AMD then it will skip the section you are having trouble with.

Cross your fingers and let me know how you do.

**Comment by Hubfront** [comment]
Hi slyfox,

thank you for the update. Executing your script on Garuda fails with the error message below:


-------------------------
|                         |
| Installing Global Tools |
|                         |
-------------------------

Building m4 - version latest
========================================================
Downloading "https://ftp.gnu.org/gnu/m4/m4-latest.tar.xz" saving as "m4-latest.tar.xz"
Download Completed
File extracted: m4-latest.tar.xz

$ ./configure --prefix=/usr/local --build=x86_64-linux-gnu --host=x86_64-linux-gnu --target=x86_64-linux-gnu --disable-nls --enable-c++ --enable-threads=posix
$ make -j16
$ sudo make install

Building autoconf - version latest
========================================================
Downloading "http://ftp.gnu.org/gnu/autoconf/autoconf-latest.tar.xz" saving as "autoconf-latest.tar.xz"
Download Completed
File extracted: autoconf-latest.tar.xz

$ autoreconf -fi
$ ./configure --prefix=/usr/local --build=x86_64-linux-gnu --host=x86_64-linux-gnu M4=/usr/local/bin/m4
$ make -j16
$ sudo make install

Building libtool - version 2.4.6
========================================================
Downloading "https://ftp.gnu.org/gnu/libtool/libtool-2.4.6.tar.xz" saving as "libtool-2.4.6.tar.xz"
Download Completed
File extracted: libtool-2.4.6.tar.xz

$ ./configure --prefix=/usr/local --build=x86_64-linux-gnu --host=x86_64-linux-gnu --with-pic M4=/usr/local/bin/m4
$ make -j16
$ sudo make install

Building pkg-config - version 0.29.2
========================================================
Downloading "https://pkgconfig.freedesktop.org/releases/pkg-config-0.29.2.tar.gz" saving as "pkg-config-0.29.2.tar.gz"
Download Completed
File extracted: pkg-config-0.29.2.tar.gz

aclocal.m4:17: warning: this file was generated for autoconf 2.69.
You have another version of autoconf.  It may work, but is not guaranteed to.
If you have problems, you may need to regenerate the build system entirely.
To do so, use the procedure documented by the package, typically 'autoreconf'.
$ ./configure --prefix=/usr/local --with-pc-path=/home/matthias/Downloads/ffmpeg-build-script/ffmpeg-build-script/workspace/lib64/pkgconfig:/home/matthias/Downloads/ffmpeg-build-script/ffmpeg-build-script/workspace/lib/x86_64-linux-gnu/pkgconfig:/home/matthias/Downloads/ffmpeg-build-script/ffmpeg-build-script/workspace/lib/pkgconfig:/home/matthias/Downloads/ffmpeg-build-script/ffmpeg-build-script/workspace/share/pkgconfig:/usr/local/lib64/pkgconfig:/usr/local/lib/x86_64-linux-gnu/pkgconfig:/usr/local/lib/pkgconfig:/usr/local/share/pkgconfig:/usr/lib64/pkgconfig:/usr/lib/pkgconfig:/usr/lib/x86_64-linux-gnu/pkgconfig:/usr/share/pkgconfig:/lib64/pkgconfig:/lib/x86_64-linux-gnu/pkgconfig:/lib/pkgconfig
$ make -j16
$ sudo make install

Building librist - version git
========================================================
Downloading https://code.videolan.org/rist/librist.git as librist-git
Successfully cloned: /home/matthias/Downloads/ffmpeg-build-script/ffmpeg-build-script/packages/librist-git

$ meson setup build --prefix=/home/matthias/Downloads/ffmpeg-build-script/ffmpeg-build-script/workspace --buildtype=release --default-library=static --strip -Dstatic_analyze=true -Dtest=false

Failed to execute: meson setup build --prefix=/home/matthias/Downloads/ffmpeg-build-script/ffmpeg-build-script/workspace --buildtype=release --default-library=static --strip -Dstatic_analyze=true -Dtest=false

To report a bug create an issue at: https://github.com/slyfox1186/ffmpeg-build-script/issues
