### ISSUE TITLE
pulseaudio in static mode,no static linking 

### ISSUE THREAD

**Issue by brutus009** [slyfox1186/ffmpeg-build-script#24]
helo, 
can we make pulseaudio staticly ?

**Comment by brutus009** [comment]
i got it  :)
root@vmi1508026:~/ffmpeg-static# ldd bin/ffmpeg
        not a dynamic executable
root@vmi1508026:~/ffmpeg-static# bin/ffmpeg -buildconf
ffmpeg version cdd0c5f-Brutus_Core_Full_Static_FFmpeg_By_Rocma_Brutus Copyright (c) 2000-2023 the FFmpeg developers
  built with gcc 12 (Ubuntu 12.3.0-1ubuntu1~22.04)
  configuration: --prefix=/root/ffmpeg-static/target --bindir=/root/ffmpeg-static/bin --target-os=linux --arch=x86_64 --disable-shared --disable-debug --disable-doc --disable-large-tests --disable-schannel --disable-libmfx --enable-cross-compile --enable-static --enable-pic --enable-ffplay --enable-fontconfig --enable-frei0r --enable-gpl --enable-version3 --enable-nonfree --enable-libfribidi --enable-libfdk-aac --enable-libfreetype --enable-libmp3lame --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenjpeg --enable-libopus --enable-libspeex --enable-libtheora --enable-libvo-amrwbenc --enable-libvorbis --enable-libvpx --enable-libwebp --enable-libx264 --enable-libxvid --enable-libzimg --enable-zlib --enable-openssl --enable-libssh --enable-librtmp --enable-libxcb --enable-lzma --enable-vulkan --enable-gmp --enable-iconv --enable-libzvbi --enable-libopenh264 --enable-libtwolame --enable-libdrm --enable-libaribb24 --enable-libsrt --enable-libaom --enable-libxml2 --enable-libx265 --enable-libsvtav1 --enable-chromaprint --enable-libdav1d --enable-libgme --enable-libkvazaar --enable-libsoxr --enable-avisynth --enable-libshaderc --enable-libass --enable-amf --enable-libvidstab --enable-libuavs3d --enable-libvmaf --enable-opencl --enable-libdavs2 --enable-ffnvcodec --enable-libbluray --enable-librist --enable-librubberband --enable-cuda-nvcc --enable-cuda-llvm --enable-cuvid --enable-nvdec --enable-nvenc --enable-lcms2 --enable-libplacebo --enable-libvpl --enable-libopenmpt --enable-librav1e --enable-libxavs2 --enable-lv2 --enable-libjxl --enable-libpulse --enable-sdl2 --enable-xlib --enable-vaapi --enable-libmodplug --enable-ladspa --enable-lto --enable-libflite --enable-libcdio --enable-libbs2b --enable-libv4l2 --enable-libsnappy --enable-vapoursynth --enable-libtesseract --enable-libcaca --enable-libfontconfig --enable-libshine --enable-libmysofa --enable-openal --enable-pthreads --pkg-config-flags=--static --extra-ldexeflags=-static --extra-cflags='-pthread -lvulkan -lmodplug -Lopus -lpulse -lpulse-simple -lpulse-mainloop-glib -lpulsecommon-14.2 -lOpenCL -lopenal -static-libgcc -static-libstdc++ -D_REENTRANT -DLZMA_API_STATIC -DLIBTWOLAME_STATIC -DJXL_STATIC_DEFINE -DJXL_CMS_STATIC_DEFINE -DJXL_THREADS_STATIC_DEFINE -DAL_LIBTYPE_STATIC' --extra-ldflags=-pthread --extra-libs='-liconv -lcharset -lFLAC -lcrypto -lssl -lxcb -lXau -lXdmcp -lsndfile -lgraphite2 -lass -laribb24 -lpng16 -llcms2 -llcms2_threaded -lsamplerate -lfftw3 -lgmp -lchromaprint -lplacebo -ljxl -ljxl_cms -ljxl_threads -lfreetype -lasound -lbz2 -llz4 -lzstd -lnettle -ljbig -ldeflate -lmysofa -lv4l2 -lxml2 -lvapoursynth-script -lpython3.10 -lcrypt -ldl -lvapoursynth -lzimg -lexpat -lcaca -lncurses -ltinfo -lslang -lstdc++ -llzma -lswscale -lm -latomic -lpthread -lrt -lgomp -lz' --extra-version=Brutus_Core_Full_Static_FFmpeg_By_Rocma_Brutus
  libavutil      58. 29.100 / 58. 29.100
  libavcodec     60. 31.102 / 60. 31.102
  libavformat    60. 16.100 / 60. 16.100
  libavdevice    60.  3.100 / 60.  3.100
  libavfilter     9. 12.100 /  9. 12.100
  libswscale      7.  5.100 /  7.  5.100
  libswresample   4. 12.100 /  4. 12.100
  libpostproc    57.  3.100 / 57.  3.100

  configuration:
    --prefix=/root/ffmpeg-static/target
    --bindir=/root/ffmpeg-static/bin
    --target-os=linux
    --arch=x86_64
    --disable-shared
    --disable-debug
    --disable-doc
    --disable-large-tests
    --disable-schannel
    --disable-libmfx
    --enable-cross-compile
    --enable-static
    --enable-pic
    --enable-ffplay
    --enable-fontconfig
    --enable-frei0r
    --enable-gpl
    --enable-version3
    --enable-nonfree
    --enable-libfribidi
    --enable-libfdk-aac
    --enable-libfreetype
    --enable-libmp3lame
    --enable-libopencore-amrnb
    --enable-libopencore-amrwb
    --enable-libopenjpeg
    --enable-libopus
    --enable-libspeex
    --enable-libtheora
    --enable-libvo-amrwbenc
    --enable-libvorbis
    --enable-libvpx
    --enable-libwebp
    --enable-libx264
    --enable-libxvid
    --enable-libzimg
    --enable-zlib
    --enable-openssl
    --enable-libssh
    --enable-librtmp
    --enable-libxcb
    --enable-lzma
    --enable-vulkan
    --enable-gmp
    --enable-iconv
    --enable-libzvbi
    --enable-libopenh264
    --enable-libtwolame
    --enable-libdrm
    --enable-libaribb24
    --enable-libsrt
    --enable-libaom
    --enable-libxml2
    --enable-libx265
    --enable-libsvtav1
    --enable-chromaprint
    --enable-libdav1d
    --enable-libgme
    --enable-libkvazaar
    --enable-libsoxr
    --enable-avisynth
    --enable-libshaderc
    --enable-libass
    --enable-amf
    --enable-libvidstab
    --enable-libuavs3d
    --enable-libvmaf
    --enable-opencl
    --enable-libdavs2
    --enable-ffnvcodec
    --enable-libbluray
    --enable-librist
    --enable-librubberband
    --enable-cuda-nvcc
    --enable-cuda-llvm
    --enable-cuvid
    --enable-nvdec
    --enable-nvenc
    --enable-lcms2
    --enable-libplacebo
    --enable-libvpl
    --enable-libopenmpt
    --enable-librav1e
    --enable-libxavs2
    --enable-lv2
    --enable-libjxl
    --enable-libpulse
    --enable-sdl2
    --enable-xlib
    --enable-vaapi
    --enable-libmodplug
    --enable-ladspa
    --enable-lto
    --enable-libflite
    --enable-libcdio
    --enable-libbs2b
    --enable-libv4l2
    --enable-libsnappy
    --enable-vapoursynth
    --enable-libtesseract
    --enable-libcaca
    --enable-libfontconfig
    --enable-libshine
    --enable-libmysofa
    --enable-openal
    --enable-pthreads
    --pkg-config-flags=--static
    --extra-ldexeflags=-static
    --extra-cflags='-pthread -lvulkan -lmodplug -Lopus -lpulse -lpulse-simple -lpulse-mainloop-glib -lpulsecommon-14.2 -lOpenCL -lopenal -static-libgcc -static-libstdc++ -D_REENTRANT -DLZMA_API_STATIC -DLIBTWOLAME_STATIC -DJXL_STATIC_DEFINE -DJXL_CMS_STATIC_DEFINE -DJXL_THREADS_STATIC_DEFINE -DAL_LIBTYPE_STATIC'
    --extra-ldflags=-pthread
    --extra-libs='-liconv -lcharset -lFLAC -lcrypto -lssl -lxcb -lXau -lXdmcp -lsndfile -lgraphite2 -lass -laribb24 -lpng16 -llcms2 -llcms2_threaded -lsamplerate -lfftw3 -lgmp -lchromaprint -lplacebo -ljxl -ljxl_cms -ljxl_threads -lfreetype -lasound -lbz2 -llz4 -lzstd -lnettle -ljbig -ldeflate -lmysofa -lv4l2 -lxml2 -lvapoursynth-script -lpython3.10 -lcrypt -ldl -lvapoursynth -lzimg -lexpat -lcaca -lncurses -ltinfo -lslang -lstdc++ -llzma -lswscale -lm -latomic -lpthread -lrt -lgomp -lz'
    --extra-version=Brutus_Core_Full_Static_FFmpeg_By_Rocma_Brutus

**Comment by brutus009** [comment]
i make it staicly with old version 14.2, i think its the last version with static link , on the new version the meson system dont allow static linking for pulseaudio i dont know why.

**Comment by brutus009** [comment]
and booom last vertsion too staticly linked :)

**Comment by brutus009** [comment]
full static bin 👍 
I forgot something??
`
/brutus-static# ldd bin/ffmpeg
        not a dynamic executable 👍 
/brutus-static# bin/ffmpeg -buildconf
ffmpeg version 6.1-Brutus_Core_Full_Static_FFmpeg_By_Rocma_Brutus Copyright (c) 2000-2023 the FFmpeg developers
  built with gcc 12 (Ubuntu 12.3.0-1ubuntu1~22.04)
  configuration: --prefix=/root/brutus-static/install --bindir=/root/brutus-static/bin --target-os=linux --arch=x86_64 --disable-shared --disable-debug --disable-doc --disable-large-tests --disable-schannel --disable-libmfx --disable-ptx-compression --enable-cross-compile --enable-static --enable-pic --enable-ffplay --enable-fontconfig --enable-frei0r --enable-gpl --enable-version3 --enable-nonfree --enable-libfribidi --enable-libfdk-aac --enable-libfreetype --enable-libmp3lame --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenjpeg --enable-libopus --enable-libspeex --enable-libtheora --enable-libvo-amrwbenc --enable-libvorbis --enable-libvpx --enable-libwebp --enable-libx264 --enable-libxvid --enable-libzimg --enable-zlib --enable-openssl --enable-libssh --enable-librtmp --enable-libxcb --enable-lzma --enable-vulkan --enable-gmp --enable-iconv --enable-libzvbi --enable-libopenh264 --enable-libtwolame --enable-libdrm --enable-libaribb24 --enable-libsrt --enable-libaom --enable-libxml2 --enable-libx265 --enable-libsvtav1 --enable-chromaprint --enable-libdav1d --enable-libgme --enable-libkvazaar --enable-libsoxr --enable-avisynth --enable-libshaderc --enable-libass --enable-amf --enable-libvidstab --enable-libuavs3d --enable-libvmaf --enable-opencl --enable-libdavs2 --enable-ffnvcodec --enable-libbluray --enable-librist --enable-librubberband --enable-cuda-nvcc --enable-cuda-llvm --enable-cuvid --enable-nvdec --enable-nvenc --enable-lcms2 --enable-libplacebo --enable-libvpl --enable-libopenmpt --enable-librav1e --enable-libxavs2 --enable-lv2 --enable-libjxl --enable-libpulse --enable-sdl2 --enable-xlib --enable-vaapi --enable-libmodplug --enable-ladspa --enable-libflite --enable-libcdio --enable-libbs2b --enable-libv4l2 --enable-libsnappy --enable-vapoursynth --enable-libtesseract --enable-libcaca --enable-libfontconfig --enable-libshine --enable-libmysofa --enable-openal --enable-libnpp --enable-pthreads --nvccflags='-gencode arch=compute_61,code=sm_61 -gencode arch=compute_70,code=sm_70 -gencode arch=compute_75,code=sm_75 -gencode arch=compute_86,code=sm_86 -gencode arch=compute_89,code=sm_89 -gencode arch=compute_90,code=sm_90' --pkg-config-flags=--static --extra-ldexeflags=-static --extra-ldflags=-pthread --extra-cflags='-lvulkan -lmodplug -Lopus -lpulse -lpulse-simple -lpulse-mainloop-glib -lpulsecommon-16.99 -lOpenCL -lopenal -static-libgcc -static-libstdc++ -pthread -D_REENTRANT -DLZMA_API_STATIC -DLIBTWOLAME_STATIC -DJXL_STATIC_DEFINE -DJXL_CMS_STATIC_DEFINE -DJXL_THREADS_STATIC_DEFINE -DAL_LIBTYPE_STATIC' --extra-libs='-lculibos -lcudart -lnppial -lnppicc -lnppidei -lnppif -lnppig -lnppim -lnppist -lnppisu -lnppitc -lnpps -lnppc -liconv -lcharset -lFLAC -lcrypto -lssl -lxcb -lXau -lXdmcp -lsndfile -lgraphite2 -lass -laribb24 -lpng16 -llcms2 -llcms2_threaded -lsamplerate -lfftw3 -lgmp -lchromaprint -lplacebo -ljxl -ljxl_cms -ljxl_threads -lfreetype -lasound -lbz2 -llz4 -lzstd -lnettle -ljbig -ldeflate -lmysofa -lv4l2 -lxml2 -lvapoursynth-script -lpython3.10 -lcrypt -ldl -lvapoursynth -lzimg -lexpat -lcaca -lncurses -ltinfo -lslang -lstdc++ -llzma -lswscale -lm -latomic -lpthread -lrt -lgomp -lz' --extra-version=Brutus_Core_Full_Static_FFmpeg_By_Rocma_Brutus
  libavutil      58. 29.100 / 58. 29.100
  libavcodec     60. 31.102 / 60. 31.102
  libavformat    60. 16.100 / 60. 16.100
  libavdevice    60.  3.100 / 60.  3.100
  libavfilter     9. 12.100 /  9. 12.100
  libswscale      7.  5.100 /  7.  5.100
  libswresample   4. 12.100 /  4. 12.100
  libpostproc    57.  3.100 / 57.  3.100

  configuration:
    --prefix=/root/brutus-static/install
    --bindir=/root/brutus-static/bin
    --target-os=linux
    --arch=x86_64
    --disable-shared
    --disable-debug
    --disable-doc
    --disable-large-tests
    --disable-schannel
    --disable-libmfx
    --disable-ptx-compression
    --enable-cross-compile
    --enable-static
    --enable-pic
    --enable-ffplay
    --enable-fontconfig
    --enable-frei0r
    --enable-gpl
    --enable-version3
    --enable-nonfree
    --enable-libfribidi
    --enable-libfdk-aac
    --enable-libfreetype
    --enable-libmp3lame
    --enable-libopencore-amrnb
    --enable-libopencore-amrwb
    --enable-libopenjpeg
    --enable-libopus
    --enable-libspeex
    --enable-libtheora
    --enable-libvo-amrwbenc
    --enable-libvorbis
    --enable-libvpx
    --enable-libwebp
    --enable-libx264
    --enable-libxvid
    --enable-libzimg
    --enable-zlib
    --enable-openssl
    --enable-libssh
    --enable-librtmp
    --enable-libxcb
    --enable-lzma
    --enable-vulkan
    --enable-gmp
    --enable-iconv
    --enable-libzvbi
    --enable-libopenh264
    --enable-libtwolame
    --enable-libdrm
    --enable-libaribb24
    --enable-libsrt
    --enable-libaom
    --enable-libxml2
    --enable-libx265
    --enable-libsvtav1
    --enable-chromaprint
    --enable-libdav1d
    --enable-libgme
    --enable-libkvazaar
    --enable-libsoxr
    --enable-avisynth
    --enable-libshaderc
    --enable-libass
    --enable-amf
    --enable-libvidstab
    --enable-libuavs3d
    --enable-libvmaf
    --enable-opencl
    --enable-libdavs2
    --enable-ffnvcodec
    --enable-libbluray
    --enable-librist
    --enable-librubberband
    --enable-cuda-nvcc
    --enable-cuda-llvm
    --enable-cuvid
    --enable-nvdec
    --enable-nvenc
    --enable-lcms2
    --enable-libplacebo
    --enable-libvpl
    --enable-libopenmpt
    --enable-librav1e
    --enable-libxavs2
    --enable-lv2
    --enable-libjxl
    --enable-libpulse
    --enable-sdl2
    --enable-xlib
    --enable-vaapi
    --enable-libmodplug
    --enable-ladspa
    --enable-libflite
    --enable-libcdio
    --enable-libbs2b
    --enable-libv4l2
    --enable-libsnappy
    --enable-vapoursynth
    --enable-libtesseract
    --enable-libcaca
    --enable-libfontconfig
    --enable-libshine
    --enable-libmysofa
    --enable-openal
    --enable-libnpp
    --enable-pthreads
    --nvccflags='-gencode arch=compute_61,code=sm_61 -gencode arch=compute_70,code=sm_70 -gencode arch=compute_75,code=sm_75 -gencode arch=compute_86,code=sm_86 -gencode arch=compute_89,code=sm_89 -gencode arch=compute_90,code=sm_90'
    --pkg-config-flags=--static
    --extra-ldexeflags=-static
    --extra-ldflags=-pthread
    --extra-cflags='-lvulkan -lmodplug -Lopus -lpulse -lpulse-simple -lpulse-mainloop-glib -lpulsecommon-16.99 -lOpenCL -lopenal -static-libgcc -static-libstdc++ -pthread -D_REENTRANT -DLZMA_API_STATIC -DLIBTWOLAME_STATIC -DJXL_STATIC_DEFINE -DJXL_CMS_STATIC_DEFINE -DJXL_THREADS_STATIC_DEFINE -DAL_LIBTYPE_STATIC'
    --extra-libs='-lculibos -lcudart -lnppial -lnppicc -lnppidei -lnppif -lnppig -lnppim -lnppist -lnppisu -lnppitc -lnpps -lnppc -liconv -lcharset -lFLAC -lcrypto -lssl -lxcb -lXau -lXdmcp -lsndfile -lgraphite2 -lass -laribb24 -lpng16 -llcms2 -llcms2_threaded -lsamplerate -lfftw3 -lgmp -lchromaprint -lplacebo -ljxl -ljxl_cms -ljxl_threads -lfreetype -lasound -lbz2 -llz4 -lzstd -lnettle -ljbig -ldeflate -lmysofa -lv4l2 -lxml2 -lvapoursynth-script -lpython3.10 -lcrypt -ldl -lvapoursynth -lzimg -lexpat -lcaca -lncurses -ltinfo -lslang -lstdc++ -llzma -lswscale -lm -latomic -lpthread -lrt -lgomp -lz'
    --extra-version=Brutus_Core_Full_Static_FFmpeg_By_Rocma_Brutus

`

**Comment by slyfox1186** [comment]
I have no plans for this at this time. If you have more to share I will listen to what you have found. Thanks.
