### ISSUE TITLE
static libnpp missing file nppi.a

### ISSUE THREAD

**Issue by brutus009** [slyfox1186/ffmpeg-build-script#25]
helo i try to make a static linking of libnpp , im blocked here : 
static libnpp missing file nppi.a
any idea how to do that ?

**Comment by slyfox1186** [comment]
OLD: My bet is on a VPN. Do you have access to that?

NEW: Read the original response wrong I think. The best thing I can think of is Google the error log and ask chatGPT.

**Comment by slyfox1186** [comment]
Let me know if you make any progress. I will be working on the script over the next few days.

**Comment by brutus009** [comment]
yes no need  nppi.a you need to add the extra libs correctly :  -lculibos -lcudart -lnppial -lnppicc -lnppidei -lnppif -lnppig -lnppim -lnppist -lnppisu -lnppitc -lnpps -lnppc 

like this ffmpeg dont ask for nppi.a
