### ISSUE TITLE
Have the ability to create a patent-free version of the binaries

### ISSUE THREAD

**Issue by jeanslack** [slyfox1186/ffmpeg-build-script#27]
Hi, 
I find this project interesting, however I would be very grateful if you could also provide a version of this script that builds a patent-free FFmpeg version based only on GPL codecs, specifying `--enable-gpl --enable -version3` in the configure licensing options.

**Comment by slyfox1186** [comment]
Yeah I can take a look into this. Just keep tabs on my progress.

**Comment by slyfox1186** [comment]
I have added this ability to the script. Just pass `--enable-gpl-and-non-free` to the script to build a non-free version or omit it to build a GNU (free) version of FFmpeg.

I let FFmpeg tell me whether or not a program was free so I only know if they are based on that. You must do your own research to ensure you are not infringing on someone's intellectual property yourself.
