### ISSUE TITLE
dirname: missing operand

### ISSUE THREAD

**Issue by laryan61** [slyfox1186/ffmpeg-build-script#28]
I ran into to errors running your script.
I using Linux Mint 20.2

Installing the required APT packages
========================================================
Checking installation status of each package...
dirname: missing operand

Looking at the code, in my directory "/usr/lib/jvm/", there are no files containing 'javac'. it does contain the files; .java-1.8.0-openjdk-amd64.jinfo & .java-1.11.0-openjdk-amd64.jinfo

Then later.
$ ./configure --prefix=/home/username/ffmpeg-build-script/ffmpeg-build-script/workspace --build=x86_64-linux-gnu --host=x86_64-linux-gnu --target=x86_64-linux-gnu --disable-nls --enable-c++ --enable-threads=posix

Error: Failed to execute ./configure --prefix=/home/username/ffmpeg-build-script/ffmpeg-build-script/workspace --build=x86_64-linux-gnu --host=x86_64-linux-gnu --target=x86_64-linux-gnu --disable-nls --enable-c++ --enable-threads=posix

The directory /home/username/ffmpeg-build-script/ffmpeg-build-script/workspace didn't exist.

**Comment by slyfox1186** [comment]
what version of Linux are you running?
make sure you have the latest version of the script.

you need javac. you must install an `openjdk` package that comes with it. tell me the package name after it works so i can add it to the script.

Regarding the missing directory, the script should have made the folder `"$workspace"`. if for any reason it does not do this, add this to the script after the variables are defined at the top of the script using the command `mkdir -p "$workspace"`

**Comment by laryan61** [comment]
Script version: 3.4.7, Updated: 02.10.24
So at that time, it was the latest version. I'm running Ubuntu version 20.03. Which version of the JDK 6, 7 or 8 should I install?

I see where "workspace" is defined, but no where in the script do I see where the $workspace directory is created.

edit. corrected Ubuntu version.

**Comment by slyfox1186** [comment]
Please update the script to the latest version.

What is version 20.3?

Ubuntu Focal's version is is 20.04...

The workspace variable is defined in the latest script for sure.

**Comment by laryan61** [comment]
Downloaded latest build tonight. I got this error. There is/was no directory "/home/user/ffmpeg-build-script/ffmpeg-build-script/workspace" created. I've attached your script as it was installed from git.
[build-ffmpeg.sh.txt](https://github.com/slyfox1186/ffmpeg-build-script/files/14474997/build-ffmpeg.sh.txt)


Building m4 - version latest
========================================================
Downloading "https://ftp.gnu.org/gnu/m4/m4-latest.tar.xz" saving as "m4-latest.tar.xz"
Download Completed
File extracted: m4-latest.tar.xz

$ ./configure --prefix=/home/user/ffmpeg-build-script/ffmpeg-build-script/workspace --disable-nls --enable-c++ --enable-threads=posix

[ERROR] Failed to execute ./configure --prefix=/home/user/ffmpeg-build-script/ffmpeg-build-script/workspace --disable-nls --enable-c++ --enable-threads=posix

**Comment by slyfox1186** [comment]
Line 121 has been edited to `mkdir -p "$packages" "$workspace"`

This should take care of the missing workspace directory.

**Comment by slyfox1186** [comment]
If this is still an issue re-open this.
