### ISSUE TITLE
NVIDIA Quadro P2000 Not Detected Error

### ISSUE THREAD

**Issue by johnwchambers** [slyfox1186/ffmpeg-build-script#3]
I have a NVIDIA Quadro P2000 card that is not detected. The script is running through just fine and then errors out with the following:

Unable to define the variable "gpu_type" in the function "gpu_arch_fn":Line 548.

My nvidia-smi output is below:

    +---------------------------------------------------------------------------------------+
    | NVIDIA-SMI 535.113.01             Driver Version: 535.113.01   CUDA Version: 12.2     |
    |-----------------------------------------+----------------------+----------------------+
    | GPU  Name                 Persistence-M | Bus-Id        Disp.A | Volatile Uncorr. ECC |
    | Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
    |                                         |                      |               MIG M. |
    |=========================================+======================+======================|
    |   0  Quadro P2000                   Off | 00000000:17:00.0 Off |                  N/A |
    | 56%   53C    P0              21W /  75W |    137MiB /  5120MiB |      6%      Default |
    |                                         |                      |                  N/A |
    +-----------------------------------------+----------------------+----------------------+

    +---------------------------------------------------------------------------------------+
    | Processes:                                                                            |
    |  GPU   GI   CI        PID   Type   Process name                            GPU Memory |
    |        ID   ID                                                             Usage      |
    |=======================================================================================|
    |    0   N/A  N/A    592194      C   ...lib/plexmediaserver/Plex Transcoder      133MiB |
    +---------------------------------------------------------------------------------------+

**Comment by johnwchambers** [comment]
So I bypassed the error by adding the following into the list of GPU cards. I'm assuming that since the GTX 1060 is the same family as the P2000 that it had to be the same GPU type. 

    'Quadro P2000')               gpu_type=1;;

However, now I've ran into another error, the following:

    Building ffmpeg - version 963937e
    ====================================
    Downloading "https://git.ffmpeg.org/gitweb/ffmpeg.git/snapshot/963937e408fc68b5925f938a253cfff1d506f784.tar.gz" saving as "ffmpeg-963937e.tar.gz"
    Download Completed
    File extracted: ffmpeg-963937e.tar.gz

    ERROR: libssh not found using pkg-config

Resolved the above error by installing the libssh-dev package and then re-running the build script.

**Comment by slyfox1186** [comment]
Nice job figuring that out. I will add this to the script. Thank you!
