### ISSUE TITLE
Failed to build autoconf 2.7.1 (Ubuntu WSL)

### ISSUE THREAD

**Issue by fozter** [slyfox1186/ffmpeg-build-script#30]
Failing on building autoconf, running fresh Ubuntu 22.04 WSL (full log attached)

```
Building autoconf - version 2.71
========================================================
Downloading "https://ftp.gnu.org/gnu/autoconf/autoconf-2.71.tar.xz" saving as "autoconf-2.71.tar.xz"
Download Completed
File extracted: autoconf-2.71.tar.xz

$ autoreconf -fi

[ERROR] Failed to execute autoreconf -fi
```

[log.txt](https://github.com/slyfox1186/ffmpeg-build-script/files/15216106/log.txt)

**Comment by slyfox1186** [comment]
1. Download the latest version of the script as of today to make sure we are working on the same script together.
2. Turn `debug=OFF` to `debug=ON` and run the script again and post the logs.

I ran this on WSL Ubuntu 22.04 today and did not get the same error that you reported so I will need to see the verbose logs before I will have an idea of what might be wrong with your install.

**Comment by fozter** [comment]
There you go [log.txt](https://github.com/slyfox1186/ffmpeg-build-script/files/15281276/log.txt)

**Comment by slyfox1186** [comment]
This didn't show me enough like I had hoped it would so next do this.

```
cd ffmpeg-build-script/packages/libzstd-1.5.6
clear
sudo meson setup build --prefix=/home/kongo/ffmpeg-build-script/workspace --buildtype=release --default-library=both --strip -Dbin_tests=false
```

If that meson command does not work then try this command

```
sudo meson setup build --reconfigure --prefix=/home/kongo/ffmpeg-build-script/workspace --buildtype=release --default-library=both --strip -Dbin_tests=false
```
Send me the logs again. This time it should show you way more output.

Also, it appears you got past the first hurdle huh?

**Comment by fozter** [comment]
Got "ERROR: Neither directory contains a build file meson.build." with both lines, so i tried to simply install meson with apt. Don't know if it's the wrong way to do it, im kind of a newbie when it comes to building/compiling.

Anyway, it got a little further untill it failed on building giflib. 
[log.txt](https://github.com/slyfox1186/ffmpeg-build-script/files/15281537/log.txt)

**Comment by slyfox1186** [comment]
have you modified any of the default variables in .bashrc? Like the PATH variable?

I'm not having any of these issues. I'm even able to build this on WSL debian.

I even resorted to asking AI for it's opinion on the matter.

Here is what it had to say.

```markdown
This snippet shows the commands used to build and install giflib version 5.2.2. The error you're experiencing with the SONAME might not be directly related to this script unless it's missing some configuration or setup that specifies the SONAME during the build. Here are a couple of steps you can take to investigate further or potentially resolve the issue:

1. **Ensure Proper Configuration**: Check the `configure` script or equivalent in the giflib source directory to see if there's a flag or option to set the SONAME. It’s possible that you might need to manually specify this during the configuration step if giflib uses such a script.

2. **Check Makefile**: Dive into the Makefile of giflib to see if there's a step where the SONAME is supposed to be set. Sometimes, this might be missing or not properly configured.

3. **Explicitly Set SONAME**: If giflib’s build system supports it, you might need to explicitly pass the SONAME during the linking step. This could involve modifying the Makefile or passing additional parameters to `make`.

4. **Update Build Script**: If you find that a specific flag or setting is required to properly set the SONAME, you should update your script to include this during the build process.

If none of these steps reveal a straightforward solution, I recommend checking the documentation or forums associated with giflib for any known issues or required configurations specific to your version or environment.

Should you need specific changes to the script based on the findings or further assistance to debug the make process of giflib, feel free to ask!
```

**Comment by slyfox1186** [comment]
I think you giflib issue is caused by a lack of imagemagick being installed. I will update the script this evening. Sorry you have had so much trouble. Hopefully we are getting to the bottom of the issues.

**Comment by fozter** [comment]
No worries, i suspected it was something with giflib itself so i tried with setting it to 5.2.1 and then it worked all the way through.
Thank you for the help and the script itself
