### ISSUE TITLE
Script fails at building Openssl

### ISSUE THREAD

**Issue by deadsound** [slyfox1186/ffmpeg-build-script#39]
Script runs up until it get to building openssl then it fails. I noticed there is no version number like the other's packages. Could be why the script fails.  
"https://www.openssl.org/source/openssl-.tar.gz "   There is no version number after the "openssl-xxx" so the download fails.

Please see below.

Building openssl - version 
========================================================
[INFO] Downloading "https://www.openssl.org/source/openssl-.tar.gz" saving as "openssl-.tar.gz"
[INFO] Download Completed

[ERROR] Failed to extract the tarball "openssl-.tar.gz" and was deleted. Re-run the script to try again. Line: 282

[INFO] For help or to report a bug create an issue at: https://github.com/slyfox1186/ffmpeg-build-script/issues

Tried both Ubuntu 24.02 and 22.02

**Comment by ma-blip** [comment]
Change url on row 1000  in the script to https://openssl-library.org/source/ and run again

**Comment by deadsound** [comment]
thx
