### ISSUE TITLE
Script has issues when non-free repository is not enabled

### ISSUE THREAD

**Issue by simone-85** [slyfox1186/ffmpeg-build-script#4]
`lsb_release -a` :
Distributor ID:	Debian
Description:	Debian GNU/Linux 12 (bookworm)
Release:	12
Codename:	bookworm

Not enabling non-free causes some problems installing package _'libfdk-aac-dev'_ (which is part of the non-free repo)
This is solved by adding non-free repository in _/etc/apt/sources.list_

**Comment by slyfox1186** [comment]
Thanks. I can remove that entry as it is built from source code during script execution.

**Comment by slyfox1186** [comment]
Thanks. I can remove that entry as it is built from source code during script execution.
