### ISSUE TITLE
AVIF build fails

### ISSUE THREAD

**Issue by deadsound** [slyfox1186/ffmpeg-build-script#40]
Building avif fails. 

> Building avif - version 1.1.1
========================================================
[INFO] avif-1.1.1.tar.gz is already downloaded.
[INFO] File extracted: avif-1.1.1.tar.gz
$ cmake -B build -DCMAKE_INSTALL_PREFIX=/home/deadsound/Desktop/ffmpeg-build-script/workspace -DCMAKE_BUILD_TYPE=Release -DBUILD_SHARED_LIBS=OFF -DAVIF_CODEC_AOM=ON -DAVIF_CODEC_AOM_DECODE=ON -DAVIF_CODEC_AOM_ENCODE=ON -DAVIF_ENABLE_GTEST=OFF -DAVIF_ENABLE_WERROR=OFF -G Ninja -Wno-dev

[ERROR] Failed to execute cmake -B build -DCMAKE_INSTALL_PREFIX=/home/deadsound/Desktop/ffmpeg-build-script/workspace -DCMAKE_BUILD_TYPE=Release -DBUILD_SHARED_LIBS=OFF -DAVIF_CODEC_AOM=ON -DAVIF_CODEC_AOM_DECODE=ON -DAVIF_CODEC_AOM_ENCODE=ON -DAVIF_ENABLE_GTEST=OFF -DAVIF_ENABLE_WERROR=OFF -G Ninja -Wno-dev

[INFO] For help or to report a bug create an issue at: https://github.com/slyfox1186/ffmpeg-build-script/issues

**Comment by slyfox1186** [comment]
I can not reproduce this on Ubuntu or Debian. Are you still having issues with this?

**Comment by deadsound** [comment]
Works... maybe the API was down and wasn't avalible that day. thanks!
