### ISSUE TITLE
Missing dependency checks - ccache & libssl-dev

### ISSUE THREAD

**Issue by g33kphr33k** [slyfox1186/ffmpeg-build-script#41]
Hello

I love this script, thank you for it.

On Debian 12, I have found that the script runs and falls over on missing packages not globally checked for. So far, I've had to manually install **ccache** and **libssl-dev**.

Keep up the good work!

**Comment by slyfox1186** [comment]
Thanks for letting me know. I will make sure I manually install ccache and libssl-dev!
