### ISSUE TITLE
No decklink support Ubuntu 24.04

### ISSUE THREAD

**Issue by deadsound** [slyfox1186/ffmpeg-build-script#43]
Great Script! thanks for posting this... 
      I have built twice and both times no decklink support. I see the headers folder with the deckLink sdk downloads, but I don't see where --enable-deckLink  is called in teh script.. When I run the finished build the banner does not show --enable-deckLink . I have the proper divers installed and I am using Ubuntu 24.02.
      Everything else seems to work gr8!
      
      WK

**Comment by slyfox1186** [comment]
I talked with the creator of the repo I was using is not being updated anymore and it can be supported.
