### ISSUE TITLE
fonfconfig requires gperf & autopoint installed

### ISSUE THREAD

**Issue by g33kphr33k** [slyfox1186/ffmpeg-build-script#45]
Building fontconfig - version 2.15.0
========================================================
[INFO] fontconfig-2.15.0.tar.bz2 is already downloaded.
[INFO] File extracted: fontconfig-2.15.0.tar.bz2
$ autoupdate
$ ./autogen.sh --noconf

[ERROR] Failed to execute ./autogen.sh --noconf

To fix, simply install gperf (sudo apt install gperf & autopoint). It might be good to make this a globally required check at the beginning of the script.

**Comment by slyfox1186** [comment]
```
To fix, simply install gperf (sudo apt install gperf & autopoint)
```

```
sudo apt install gperf & autopoint
```

**Comment by slyfox1186** [comment]
Re-open if needed.
