### ISSUE TITLE
CMAKE Unfortunately this is still not resolved.On 11 Sep 2024, at 09:45, Jeff ***@***.***> wrote:﻿

### ISSUE THREAD

**Issue by budgierless** [slyfox1186/ffmpeg-build-script#46]
Unfortunately this is still not resolved.On 11 Sep 2024, at 09:45, Jeff ***@***.***> wrote:﻿
This should be fixed in version 4.0.0

—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: ***@***.***>

_Originally posted by @budgierless in https://github.com/slyfox1186/ffmpeg-build-script/issues/44#issuecomment-2343283959_

**Comment by slyfox1186** [comment]
Ensure you have deleted the following files in the `$packages` folder:

1. The cmake tar file that is downloaded and any folders that have been created by extracting this tar file.
2. The cmake.done file in the same folder as the above mentioned files.


I am having no issues with this and the script is designed to not like any errors what-so-ever so this would have failed had it not been successfully compiled.

```
Building libtool - version 2.4.7
========================================================
libtool version 2.4.7 already built. Remove /home/jman/tmp/ffmpeg/ffmpeg-build-script/packages/libtool.done lockfile to rebuild it.

Building pkg-config - version 0.29.2
========================================================
pkg-config version 0.29.2 already built. Remove /home/jman/tmp/ffmpeg/ffmpeg-build-script/packages/pkg-config.done lockfile to rebuild it.

Building cmake - version 3.30.3
========================================================
[INFO] cmake-3.30.3.tar.gz is already downloaded.
[INFO] File extracted: cmake-3.30.3.tar.gz
$ ./bootstrap --prefix=/home/jman/tmp/ffmpeg/ffmpeg-build-script/workspace --parallel=32 --enable-ccache
$ make -j32
$ make install

Building meson - version 1.5.1
========================================================
meson version 1.5.1 already built. Remove /home/jman/tmp/ffmpeg/ffmpeg-build-script/packages/meson.done lockfile to rebuild it.

Building ninja - version 1.12.1
========================================================
ninja version 1.12.1 already built. Remove /home/jman/tmp/ffmpeg/ffmpeg-build-script/packages/ninja.done lockfile to rebuild it.
```

**Comment by slyfox1186** [comment]
If this is still a problem let me know.
