### ISSUE TITLE
Presence of NVIDIA GPU is not mandatory for compiling with CUDA support

### ISSUE THREAD

**Issue by RealTehreal** [slyfox1186/ffmpeg-build-script#47]
It is not mandatory to have an NVIDIA GPU to compile FFMPEG with CUDA support. The only thing needed is CUDA toolkit to be installed. And this can be achieved without the presence of an NVIDIA GPU. Therefore, the script should skip looking for an NVIDIA GPU. Let the user decide, which level of compute capability to use, defaulting to 61 if unsure.

Greets

**Comment by slyfox1186** [comment]
Hmm, ok. I'll keep this in mind thanks.
