### ISSUE TITLE
collect2.exe: error: ld returned 1 exit status error

### ISSUE THREAD

**Issue by aryanrh** [slyfox1186/ffmpeg-build-script#48]
ffmpeg build is failing 

/usr/bin/ld: /root/ffmpeg-build-script/workspace/lib/libbluray.a(libbluray_la-dec.o): in function `dec_init':
dec.c:(.text+0x290): multiple definition of `dec_init'; fftools/ffmpeg_dec.o (symbol from plugin):(.text+0x0): first defined here
lto-wrapper: warning: using serial compilation of 128 LTRANS jobs
lto-wrapper: note: see the '-flto' option documentation for more information
lto-wrapper: warning: using serial compilation of 128 LTRANS jobs
lto-wrapper: note: see the '-flto' option documentation for more information
/usr/bin/ld: warning: libx265.so.199, needed by /lib/x86_64-linux-gnu/libavcodec.so.59, may conflict with libx265.so.209
/usr/bin/ld: warning: libx265.so.199, needed by /lib/x86_64-linux-gnu/libavcodec.so.59, may conflict with libx265.so.209
collect2: error: ld returned 1 exit status
make: *** [/root/ffmpeg-build-script/packages/ffmpeg-n7.0.2/Makefile:136: ffmpeg_g] Error 1

[ERROR] Failed to execute make -j16 -d
****

**Comment by slyfox1186** [comment]
go into the script and change these lines:
```
if build "x265" "3.6"; then

build_done "x265" "3.6"
```

to these lines:

```
if build "x265" "3.5"; then

build_done "x265" "3.5"
```
make sure you delete the `x265.done` file in the `$packages` folder.

**Comment by slyfox1186** [comment]
If this is still a problem let me know.
