### ISSUE TITLE
Wont build on ubuntu 24.04

### ISSUE THREAD

**Issue by joolzg** [slyfox1186/ffmpeg-build-script#52]
Building giflib - version 5.2.2
========================================================
[INFO] giflib-5.2.2.tar.gz?viasf=1 is already downloaded.
[INFO] File extracted: giflib-5.2.2.tar.gz?viasf=1
$ make
$ make PREFIX=/home/encoder/ffmpeg2/ffmpeg-build-script/workspace install

[ERROR] Failed to execute make PREFIX=/home/encoder/ffmpeg2/ffmpeg-build-script/workspace install

Running make from above in the packages/giflib-5.2.2 directory
encoder@encoder:~/ffmpeg2/ffmpeg-build-script/packages/giflib-5.2.2$ make PREFIX=/home/encoder/ffmpeg2/ffmpeg-build-script/workspace install
make -C doc
make[1]: Entering directory '/home/encoder/ffmpeg2/ffmpeg-build-script/packages/giflib-5.2.2/doc'
make[1]: Nothing to be done for 'all'.
make[1]: Leaving directory '/home/encoder/ffmpeg2/ffmpeg-build-script/packages/giflib-5.2.2/doc'
install -d "/home/encoder/ffmpeg2/ffmpeg-build-script/workspace/bin"
install gif2rgb gifbuild giffix giftext giftool gifclrmp "/home/encoder/ffmpeg2/ffmpeg-build-script/workspace/bin"
install: cannot create regular file '/home/encoder/ffmpeg2/ffmpeg-build-script/workspace/bin/gif2rgb': Permission denied
install: cannot create regular file '/home/encoder/ffmpeg2/ffmpeg-build-script/workspace/bin/gifbuild': Permission denied
install: cannot create regular file '/home/encoder/ffmpeg2/ffmpeg-build-script/workspace/bin/giffix': Permission denied
install: cannot create regular file '/home/encoder/ffmpeg2/ffmpeg-build-script/workspace/bin/giftext': Permission denied
install: cannot create regular file '/home/encoder/ffmpeg2/ffmpeg-build-script/workspace/bin/giftool': Permission denied
install: cannot create regular file '/home/encoder/ffmpeg2/ffmpeg-build-script/workspace/bin/gifclrmp': Permission denied
make: *** [Makefile:140: install-bin] Error 1

**Comment by slyfox1186** [comment]
The key here is the `Permission denied` errors. 

in the script build-ffmpeg.sh >>
go to this code block
```
if build "giflib" "5.2.2"; then
    download "https://cfhcable.dl.sourceforge.net/project/giflib/giflib-5.2.2.tar.gz?viasf=1"
    # Parellel building not available for this library
    execute make
    execute make PREFIX="$workspace" install
    build_done "giflib" "5.2.2"
fi
```

replace with

```
if build "giflib" "5.2.2"; then
    download "https://cfhcable.dl.sourceforge.net/project/giflib/giflib-5.2.2.tar.gz?viasf=1"
    # Parellel building not available for this library
    execute make
    execute sudo make PREFIX="$workspace" install
    build_done "giflib" "5.2.2"
fi
```
For reasons unknown to me some times this is all that is needed to fix a problem that really should never have been.

Report back with any errors and re-open this ticket.
