### ISSUE TITLE
Script fails if nasm/yasm is not on base system

### ISSUE THREAD

**Issue by bwanshoom** [slyfox1186/ffmpeg-build-script#54]
When compiling ffmpeg, the following error is shown:

`nasm/yasm not found or too old. Use --disable-x86asm for a crippled build.`

Executing the following resolves it:

`sudo apt-get install yasm`

This is on Zorin 17. I think yasm should be checked and installed if not present since it's required.

**Comment by slyfox1186** [comment]
Should be ok now.

**Comment by slyfox1186** [comment]
Should be ok now.
