### ISSUE TITLE
Script fails if cuda sdk is installed by the script

### ISSUE THREAD

**Issue by bwanshoom** [slyfox1186/ffmpeg-build-script#55]
If the script installs the Cuda SDK, it modifies the path in the script to include /usr/local/cuda/bin. However, the ffmpeg compilation is executed with sudo so it will never see that path and it throws an error:

`ERROR: failed checking for nvcc.`

The same is true on subsequent runs of the script because /usr/local/cuda/bin will not be in the path. One way to fix it would be to have the script ensure that /usr/local/cuda/bin is in the path and add it if not and then to pass PATH=$PATH to the sudo commands that compile ffmpeg.

**Comment by slyfox1186** [comment]
Yeah good catch. Do you know where the breakdown is happening? I have been looking and it appears it is related to the function gnu_repo().

**Comment by bwanshoom** [comment]
It's in the compilation of ffmpeg itself so lines 2840 & 2841. I worked around it by changing those to the following:

```
    execute sudo PATH="$PATH" make "-j$threads"
    execute sudo PATH="$PATH" make install

```

**Comment by slyfox1186** [comment]
Yeah that is a workaround which may be good enough. The root is deeper than that and I am going to try and figure out where it is located. If you know what I mean and know where the root of the issue is please let me know. Thanks again for helping make the script better for everyone.

**Comment by slyfox1186** [comment]
My last edits to the script which have been uploaded should have cleared this issue.
