### ISSUE TITLE
cleanup() function can wipe out the entire ffmpeg-build-script repo directory

### ISSUE THREAD

**Issue by bwanshoom** [slyfox1186/ffmpeg-build-script#56]
cleanup() calls the following:

`rm -fr "$cwd"`

This is super dangerous because it assumes the current directory is something that it may not be. There are situations where it might be the ffmpeg-build-script directory itself and it deletes everything - the base repo directory and all subdirectories.

**Comment by slyfox1186** [comment]
That was the intention.
