### ISSUE TITLE
Script doesn't cater for Linux Mint 22.x yet

### ISSUE THREAD

**Issue by bartv767** [slyfox1186/ffmpeg-build-script#57]
I have tried modifying the script to set VER and STATIC_VER to "24.04" but no success as yet. 

I will try building on a newly installed Ubuntu 24.04 and copy the executables across to the Mint installation.

**Comment by slyfox1186** [comment]
Let me know how this goes. if you can make this easy on me to implement i will add the capability.

**Comment by bartv767** [comment]
Tried to build on a fresh install of Ubuntu 24.04.1, but continued running into problems:
- Had to manually install "python3-pip" and comment out the relevant execute line
- Manually installed "meson" and comment out the execute
- Had to add "sudo" to the cp and ln libiconv.so.2 lines
- Then failed to execute the ninja install
At this point I'm afraid I ran out of time/patience. I had also found another script that successfully completed within Mint 22, with only one line needing to be removed.

Cheers, Bart

**Comment by slyfox1186** [comment]
Thanks for the help. I'll make changes based on some of your experiences.
