### ISSUE TITLE
Gpac compile issues

### ISSUE THREAD

**Issue by ma-blip** [slyfox1186/ffmpeg-build-script#6]
Hi.

Script breaks with error when compiling gpac. Ubuntu 22.04 LTS

Solved by adding 
execute sudo make "-j${cpu_threads}"

before this line in the script
execute sudo make "-j${cpu_threads}" install

Regards

**Comment by slyfox1186** [comment]
i wasn't able to find this line. I did find the line you said that "fixed it". If there are issues that I still missed just let me know.
