### ISSUE TITLE
X265 Compile issues

### ISSUE THREAD

**Issue by ma-blip** [slyfox1186/ffmpeg-build-script#7]
Hi.

Running Ubuntu 22.04 lts

Running script in home dir/ffmpeg-build-script

I had to change all execute cmake/execute ninja with sudo. Otherwise the script ended with errors.

**Comment by ma-blip** [comment]
I had no issues here on my second machine, a bit strange. Guess you can close this one.

**Comment by slyfox1186** [comment]
ok thanks for letting me know.
