### ISSUE TITLE
Libpulse - cannot open shared object file

### ISSUE THREAD

**Issue by ma-blip** [slyfox1186/ffmpeg-build-script#8]
Hi!
After compilation when trying to run ffmpeg:
error while loading shared libraries: libpulsecommon-16.99.so: cannot open shared object file: No such file or directory

Ubuntu 22.04 LTS server.

**Comment by slyfox1186** [comment]
Libpulse needs to be in this folder `/usr/lib/x86_64-linux-gnu/`

I will make changes  to the script. It should put that in there when I'm finished. Go into the build folder for libpulse and find that file and put it in the above mentioned folder.

**Comment by ma-blip** [comment]
Hi.
Im pretty sure I tried that, but I must have done something wrong. I have another machine that I need to build  on . I will try again and report back.

Keep up the good work!

**Comment by ma-blip** [comment]
I copied libpulsecommon-16.99.so to /usr/lib/x86_64-linux-gnu/ But it still throws me the same error.

ffmpeg: error while loading shared libraries: libpulsecommon-16.99.so: cannot open shared object file: No such file or directory

Regards

**Comment by ma-blip** [comment]
I copied the file by mistake to /usr/lib/x86_64-linux-gnu/pulseaudio. Works fine when its actually in the right place.
/usr/lib/x86_64-linux-gnu/

Regards

**Comment by slyfox1186** [comment]
ok very good. thank you for the support!!! also you probably had to run `sudo ldconfig` to update the libraries. that MAY have been why it didn't show as working.
