### ISSUE TITLE
Librist CPPcheck

### ISSUE THREAD

**Issue by ma-blip** [slyfox1186/ffmpeg-build-script#9]
Me again!

On a clean install of Ubuntu 22.04 LTS Librist fails to build.

Needs sudo apt install cppcheck

You might want to add that to the installer script.

Regards

====================================
Downloading https://code.videolan.org/rist/librist.git as librist-git
Successfully cloned: /home/cmpe/ffmpeg-build-script/ffmpeg-build-script/packages/librist-git

$ meson setup build --prefix=/home/cmpe/ffmpeg-build-script/ffmpeg-build-script/workspace --buildtype=release --default-library=static --strip -Dstatic_analyze=true -Dtest=false

Failed to execute: meson setup build --prefix=/home/cmpe/ffmpeg-build-script/ffmpeg-build-script/workspace --buildtype=release --default-library=static --strip -Dstatic_analyze=true -Dtest=false

**Comment by slyfox1186** [comment]
cppcheck will be added. Thank you for all the help.

**Comment by slyfox1186** [comment]
cppcheck will be added. Thank you for all the help.
